version: "3.7"

x-web: &web
  image: trojstenweb:latest
  build:
    context: .
    dockerfile: ./docker/dev/Dockerfile
  volumes:
    - .:/web

x-webenv: &webenv
  TROJSTENWEB_DATABASE_URL: db
  TROJSTENWEB_DATABASE_USER: trojsten
  TROJSTENWEB_DATABASE_NAME: trojsten
  TROJSTENWEB_DATABASE_PASSWORD: trojsten

services:
  db:
    image: postgres:12-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=trojsten
      - POSTGRES_DB=trojsten
      - POSTGRES_PASSWORD=trojsten
  web:
    <<: *web
    ports:
      - "8000:8000"
    environment:
      <<: *webenv
      DJANGO_SETTINGS_MODULE: trojsten.settings.development
      TROJSTENWEB_LOGIN_PROVIDER_URL: http://localhost:8047
      TROJSTENWEB_LOGIN_PROVIDER_INTERNAL_URL: http://login:8047
    depends_on:
      - db
      - login
    command: python -Wa manage.py runserver 0.0.0.0:8000
  login:
    <<: *web
    ports:
      - "8047:8047"
    volumes:
      - .:/web
    depends_on:
      - db
    environment:
      <<: *webenv
      DJANGO_SETTINGS_MODULE: trojsten.settings.login_dev
      TROJSTENWEB_DEVELOPMENT_SITE_ID: 10
      TROJSTENWEB_ALLOWED_HOSTS: localhost;127.0.0.1;login
    command: python -Wa manage.py runserver 0.0.0.0:8047

volumes:
  db_data:
